version: "3.8"

services:

  dbpostgres:
    image: postgres:13
    env_file:
      - .env
    container_name: pgdb
    volumes:
      - postgres_volume:/var/lib/postgresql/data
    ports:
      - 5432:5432

  django:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: django
    environment:
      - DEBUG=True
    env_file:
      - .env
    volumes:
      - .:/project
      - .:/usr/src/referral_app
    command: bash -c "python manage.py makemigrations && python manage.py migrate && python3 manage.py runserver 0.0.0.0:8000"
    ports:
      - 8000:8000
    depends_on:
      - dbpostgres

volumes:
  postgres_volume:
